app:
  baseUrl: https://${endpoint_url}

backend:
  baseUrl: https://${endpoint_url}
  listen:
    port: 7007
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      database: ${POSTGRES_DB}
      user: ${POSTGRES_USER}
      # ssl:
      #   rejectUnauthorized: false
      options:
      requestTimeout: 60000