database:
  client: pg
  connection:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    #user: backstage-qs-workload@backstage-453421.iam[this is just to show that the IAM account is trimmed when we authenticate to the cloudsql via IAM] 
    user: ${POSTGRES_USER}
    ssl:
      rejectUnauthorized: false 
options:
requestTimeout: 60000
