apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    name: backstage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: us-central1-docker.pkg.dev/backstage-460715/backstage-qs/backstage-quickstart:50f8851f-e409-4cd4-a0bb-bd6cc8801142
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http

