apiVersion: v1
kind: Service
metadata:
  labels:
    app: whereami-backend
  name: whereami-backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: whereami-backend
  type: ClusterIP
---